<script setup lang="ts">
/* global uni */
import { computed, getCurrentInstance, nextTick, watch } from "vue";
import { suggestCrop, type CropTransform, type PhotoInput } from "../../domain/photo-generation";
const props = defineProps<{ image: PhotoInput; crop: CropTransform }>();
const emit = defineEmits<{ change: [CropTransform]; confirm: [] }>();
const component=getCurrentInstance()?.proxy;const canvasId=`photo-crop-${Math.random().toString(36).slice(2)}`;
const previewApi=uni as unknown as {canvasPutImageData(options:{canvasId:string;data:Uint8ClampedArray;width:number;height:number},component?:unknown):void};
watch(()=>props.image,async(image)=>{await nextTick();previewApi.canvasPutImageData({canvasId,data:image.data,width:image.width,height:image.height},component);},{immediate:true});
function changeScale(event: Event): void { const scale = Number((event as Event & { detail: { value: number } }).detail.value); const width=props.crop.width*props.crop.scale/scale;const height=props.crop.height*props.crop.scale/scale;emit("change",{...props.crop,x:props.crop.x+(props.crop.width-width)/2,y:props.crop.y+(props.crop.height-height)/2,width,height,scale}); }
function changeAxis(axis:"x"|"y",event:Event):void{const value=Number((event as Event&{detail:{value:number}}).detail.value);emit("change",{...props.crop,[axis]:value});}
const overlayStyle=computed(()=>({left:`${props.crop.x/props.image.width*100}%`,top:`${props.crop.y/props.image.height*100}%`,width:`${props.crop.width/props.image.width*100}%`,height:`${props.crop.height/props.image.height*100}%`}));
let gesture:{x:number;y:number;distance:number;crop:CropTransform}|null=null;
function distance(touches:TouchList):number{return touches.length<2?0:Math.hypot(touches[1].clientX-touches[0].clientX,touches[1].clientY-touches[0].clientY);}
function touchstart(event:TouchEvent):void{const touch=event.touches[0];if(!touch)return;gesture={x:touch.clientX,y:touch.clientY,distance:distance(event.touches),crop:{...props.crop}};}
function touchmove(event:TouchEvent):void{if(!gesture)return;if(event.touches.length>=2&&gesture.distance>0){const scale=Math.max(1,Math.min(4,gesture.crop.scale*distance(event.touches)/gesture.distance));const width=gesture.crop.width*gesture.crop.scale/scale;const height=gesture.crop.height*gesture.crop.scale/scale;emit("change",{...gesture.crop,x:gesture.crop.x+(gesture.crop.width-width)/2,y:gesture.crop.y+(gesture.crop.height-height)/2,width,height,scale});return;}const touch=event.touches[0];if(!touch)return;const factor=props.image.width/350;emit("change",{...gesture.crop,x:gesture.crop.x-(touch.clientX-gesture.x)*factor,y:gesture.crop.y-(touch.clientY-gesture.y)*factor});}
function setRatio(ratioMode:CropTransform["ratioMode"]):void{emit("change",suggestCrop(props.image,ratioMode));}
</script>
<template><view class="cropper surface-card"><view class="ratio-row"><button @tap="setRatio('auto')">自动</button><button @tap="setRatio('square')">正方形</button><button @tap="setRatio('original')">原始比例</button><button @tap="setRatio(crop.ratioMode)">恢复建议裁剪</button></view><view class="cropper__frame" @touchstart="touchstart" @touchmove.stop.prevent="touchmove" @touchend="gesture=null"><view class="image-stage" :style="{aspectRatio:`${image.width}/${image.height}`}" loading="lazy"><canvas :canvas-id="canvasId" :id="canvasId" class="cropper__canvas" :width="image.width" :height="image.height"/><view class="crop-overlay" :style="overlayStyle"/></view><text>{{ image.width }} × {{ image.height }} px · 单指移动，双指缩放</text></view><text class="label">缩放</text><slider :value="crop.scale" :min="1" :max="4" :step="0.05" active-color="#8067a2" @change="changeScale"/><text class="label">左右</text><slider :value="crop.x" :min="0" :max="Math.max(0,image.width-crop.width)" active-color="#8067a2" @change="changeAxis('x',$event)"/><text class="label">上下</text><slider :value="crop.y" :min="0" :max="Math.max(0,image.height-crop.height)" active-color="#8067a2" @change="changeAxis('y',$event)"/><button class="primary" @tap="$emit('confirm')">确认裁剪并生成</button></view></template>
<style scoped>.cropper{padding:24rpx}.ratio-row{display:flex;gap:8rpx;margin-bottom:16rpx}.ratio-row button{flex:1;margin:0;padding:0 8rpx;border-radius:999rpx;font-size:20rpx}.cropper__frame{display:flex;min-height:360rpx;flex-direction:column;align-items:center;justify-content:center;gap:12rpx;overflow:hidden;border:2rpx dashed #cabbd8;border-radius:24rpx;background:#f3eafa;color:#655e59;font-size:22rpx}.image-stage{position:relative;width:100%;max-height:520rpx}.cropper__canvas{display:block;width:100%;height:100%}.crop-overlay{position:absolute;box-sizing:border-box;border:4rpx solid #fff;box-shadow:0 0 0 9999rpx rgba(28,24,22,.46)}.label{display:block;margin:14rpx 24rpx 0;color:#655e59;font-size:22rpx}.primary{margin-top:20rpx;color:#fff;background:var(--color-lavender-strong);border-radius:20rpx}</style>
